name: Publish Docker image

on:
  schedule:
    - cron: '00 00 */7 * *'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_TAG }}
          
      - name: Clean up previous workflow runs
        uses: egmacke/action-cleanup-workflow-runs@v1.2
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          workflow: ${{ github.workflow }}
          retain: 3

