name: Docker Nextcloud SMB

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
#   schedule:
#     - cron: '00 00 */5 * *'
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: stormshadowray/nextcloud-docker-smb

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.1.0

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{ env.REGISTRY }}
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker Metadata action
        uses: docker/metadata-action@v4.1.0
        with:
          # List of Docker images to use as base name for tags
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          # List of metadata for an image
          labels: ${{ steps.meta.outputs.labels }}
          # Push is a shorthand for --output=type=registry
          push: true
          # List of tags
          tags: ${{ steps.meta.outputs.tags }}
         
          
          
